/**
 * Every user-facing string. This is the i18n seam (§9) — nothing else in the app should
 * contain English prose.
 */
export const strings = Object.freeze({
  appName: 'polyglot',

  nav: {
    home: 'Home',
    review: 'Review',
    browse: 'Browse',
    words: 'Words',
    stats: 'Stats',
    settings: 'Settings',
    credits: 'Credits',
  },

  home: {
    greeting: 'Study',
    due: 'Due today',
    newWords: 'New words',
    streak: 'Streak',
    level: 'Level',
    xp: 'XP',
    start: 'Start review',
    startWith: (n) => `Start review · ${n} due`,
    doneToday: 'Done for today',
    allDone: 'Nothing is due. Add a word or come back tomorrow.',
    nothingYet: 'Your deck is ready. Start your first review.',
    days: (n) => (n === 1 ? '1 day' : `${n} days`),
    streakDays: (n) => (n === 1 ? '1 day streak' : `${n} day streak`),
  },

  review: {
    /** Mode eyebrow — what this card is asking (§3.2.5). */
    modes: {
      REC: 'Recall',
      LIS: 'Listening',
      PROD: 'Type the pinyin',
      SENT: 'Sentence',
      WRITE: 'Write',
    },
    progress: (done, total) => `${done} of ${total}`,
    show: 'Show answer',
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',
    typeAnswer: 'Type the pinyin',
    check: 'Check',
    correct: 'Correct',
    incorrect: 'Not quite',
    play: 'Play audio',
    replay: 'Play again',
    tapToPlay: 'Tap to play again',
    youTyped: 'You typed',
    reveal: 'Show me',
    clear: 'Clear',
    listenPrompt: 'Listen, then answer',
    writePrompt: 'Write the characters',
    sessionDone: 'Session complete',
    reviewed: (n) => `${n} reviewed`,
    backHome: 'Back to home',
    alsoRead: (pinyin) => `also ${pinyin}`,
    notSibling: (pinyin) => `not ${pinyin}`,
    hint: 'Hint',
    noAudioTitle: 'No Chinese voice installed',
    noAudioBody:
      'Your device has no Chinese speech voice, so audio is unavailable. Install one in your operating system’s language settings. Listening cards will show text instead.',
    dismiss: 'Dismiss',
  },

  browse: {
    title: 'Browse the dictionary',
    placeholder: 'Search characters, pinyin, or English',
    loading: 'Preparing the dictionary…',
    loadingHint: 'One-time setup. It runs entirely on your device.',
    noResults: 'No matches. Try the pinyin without tones, or an English word.',
    startTyping: 'Search the dictionary to add your first word.',
    resultCap: (n) => `Best ${n} matches`,
    resultCount: (n) => (n === 1 ? '1 match' : `${n} matches`),
    add: 'Add to my words',
    added: 'Added',
    addedGoTo: 'Added · up next →',
    hskBand: (n) => `HSK · band ${n}`,
    inMyWords: 'In My Words',
  },

  words: {
    title: 'My words',
    empty: 'Search the dictionary to add your first word.',
    explain: 'The HSK curriculum is always in your reviews — this page is for words you add yourself.',
    browse: 'Browse the dictionary',
    upNext: 'Up next',
    learning: 'Learning',
    due: (when) => `Due ${when}`,
    remove: 'Remove',
    removeConfirm: (word) => `Remove ${word}? Its cards go; your review history stays.`,
    removed: 'Removed',
    cancel: 'Cancel',
    count: (n) => (n === 1 ? '1 word' : `${n} words`),
  },

  word: {
    back: 'Back',
    definitions: 'Definitions',
    measureWords: 'Measure word',
    examples: 'Examples',
    otherReadings: 'Other readings',
    alsoTaught: 'Also taught separately',
    band: (n) => `HSK band ${n}`,
    custom: 'Your word',
    progress: 'Progress',
    notStarted: 'Not started yet',
    suspended: 'Locked until recognition matures',
    due: (when) => `Due ${when}`,
    noSuchWord: 'That word is not in your deck.',
  },

  stats: {
    title: 'Statistics',
    totalReviews: 'Total reviews',
    wordsStarted: 'Words started',
    passRate: 'Pass rate (30 days)',
    streak: 'Day streak',
    level: 'Level',
    perBand: 'Progress by band',
    activity: 'Last 12 weeks',
    activityLegend: (n) => (n === 1 ? '1 review' : `${n} reviews`),
    noActivity: 'No reviews',
    badges: 'Badges',
    xpBreakdown: 'Where your XP came from',
    xpShowUp: 'Showing up',
    xpReviews: 'Reviews',
    xpNewWords: 'New words',
    xpBands: 'Bands cleared',
    xpTotal: 'Total XP',
    toNextLevel: (n, level) => `${n} XP to level ${level}`,
    bandCleared: 'cleared',
    noReviews: 'Review a few words and your progress shows up here.',
    longest: (n) => `Longest: ${n === 1 ? '1 day' : `${n} days`}`,
  },

  badges: {
    band: (n) => `Band ${n} cleared`,
    streak: (n) => `${n}-day streak`,
    reviews: (n) => `${n.toLocaleString()} reviews`,
    allBands: 'Every band cleared',
    locked: 'Not yet',
  },

  settings: {
    title: 'Settings',
    study: 'Study',
    newPerDay: 'New words per day',
    maxPerDay: 'Maximum reviews per day',
    appearance: 'Appearance',
    theme: 'Theme',
    themeDark: 'Dark',
    themeLight: 'Light',
    data: 'Your data',
    dataBody: 'Everything lives on this device. Export it whenever you like.',
    export: 'Export JSON',
    import: 'Import JSON',
    importing: 'Importing…',
    imported: (n) => `Imported ${n} reviews.`,
    importFailed: 'That file is not a polyglot export. Pick the JSON you exported.',
    account: 'Account',
    accountBody: 'Sync across devices is coming. polyglot works fully without an account.',
    danger: 'Danger zone',
    dangerBody: 'This erases every review, card and custom word on this device. It cannot be undone.',
    wipe: 'Delete all local data',
    wipeConfirm: (word) => `Type ${word} to confirm`,
    wipeWord: 'DELETE',
    wipeDone: 'Local data erased.',
    cancel: 'Cancel',
  },

  account: {
    title: 'Account',
    checking: 'Checking…',
    guestBody:
      'polyglot works fully without an account. Signing in does one thing: keeps the same progress on your other devices.',
    signedOutBody: 'Signed out. Your progress is still on this device.',
    signInWith: (provider) => `Sign in with ${provider}`,
    noProviders: 'No sign-in providers are configured on this server.',
    redirecting: 'Opening sign-in…',
    verifying: 'Verifying…',
    turnstileFailed: 'The verification widget could not load. Check your connection and try again.',
    signInFailed: 'Sign-in could not start. Try again.',
    signedInAs: (name) => `Signed in as ${name}`,
    syncNow: 'Sync now',
    syncing: 'Syncing…',
    syncFailed: 'Sync failed. Your progress is safe on this device; try again.',
    syncedCounts: (pushed, pulled) => `Synced — sent ${pushed}, received ${pulled}`,
    lastSync: (when) => `Last synced ${when}`,
    never: 'never',
    justNow: 'just now',
    minutesAgo: (n) => (n === 1 ? '1 minute ago' : `${n} minutes ago`),
    hoursAgo: (n) => (n === 1 ? '1 hour ago' : `${n} hours ago`),
    signOut: 'Sign out',
    deleteAccount: 'Delete account',
    deleteBody:
      'Deletes your account and everything on the server, then erases this device. It cannot be undone.',
    deleteConfirm: (word) => `Type ${word} to confirm`,
    deleteWord: 'DELETE',
  },

  credits: {
    title: 'Credits',
    body: 'polyglot is built on freely licensed data and libraries.',
    license: 'License',
    source: 'Source data',
    home: 'Home page',
    packVersion: (v) => `Pack version ${v}`,
  },

  common: {
    loading: 'Loading…',
    error: 'Something went wrong.',
    retry: 'Retry',
    close: 'Close',
  },
});

export default strings;
