/**
 * Generates CREDITS.md and credits.json. Never hand-edit either file — edit this.
 *
 * Every upstream source the pack is built from has to appear here with its name, link
 * and license identifier. It is the attribution these licenses require, not decoration.
 */

/** @param {import('../../../config/app.config.js').AppConfig['sources']} sources */
export function buildCredits(sources, { packVersion, generatedAt }) {
  return {
    packVersion,
    generatedAt,
    sources: [
      {
        name: 'CC-CEDICT',
        description: 'Chinese-English dictionary: headwords, pinyin readings and definitions.',
        url: 'https://www.mdbg.net/chinese/dictionary?page=cc-cedict',
        downloadUrl: sources.cedictUrl,
        license: 'CC BY-SA 4.0',
        licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
      },
      {
        name: 'Tatoeba Project',
        description: 'Example sentences (Mandarin) and their English translations.',
        url: 'https://tatoeba.org/',
        downloadUrl: sources.tatoebaSentencesCmn,
        license: 'CC BY 2.0 FR',
        licenseUrl: 'https://creativecommons.org/licenses/by/2.0/fr/',
      },
      {
        name: 'HSK 3.0 word lists',
        description: 'Band assignments for the 2021 HSK 3.0 (New HSK) standard.',
        url: 'https://github.com/krmanik/HSK-3.0',
        downloadUrl: sources.hsk30Base,
        license: 'MIT',
        licenseUrl: 'https://github.com/krmanik/HSK-3.0/blob/master/LICENSE',
      },
      {
        name: 'hanzi-writer',
        description: 'Stroke-order animation and handwriting quiz rendering.',
        url: 'https://hanziwriter.org/',
        license: 'MIT',
        licenseUrl: 'https://github.com/chanind/hanzi-writer/blob/master/LICENSE',
      },
      {
        name: 'hanzi-writer-data',
        description: 'Per-character stroke outline and median data, derived from Make Me a Hanzi.',
        url: 'https://github.com/chanind/hanzi-writer-data',
        license: 'LGPL-3.0 (data derived from Make Me a Hanzi, ARPHIC Public License)',
        licenseUrl: 'https://github.com/chanind/hanzi-writer-data/blob/master/LICENSE',
      },
      {
        name: 'Noto Serif SC',
        description:
          'The serif face the hanzi are set in, subset at build time to the characters this pack uses and self-hosted.',
        url: 'https://fonts.google.com/noto/specimen/Noto+Serif+SC',
        downloadUrl: sources.notoSerifScUrl,
        license: 'SIL Open Font License 1.1',
        licenseUrl: 'https://openfontlicense.org/',
      },
      {
        name: 'Lucide',
        description: 'The UI icon set, vendored as static SVG files rather than a runtime dependency.',
        url: 'https://lucide.dev/',
        license: 'ISC',
        licenseUrl: 'https://github.com/lucide-icons/lucide/blob/main/LICENSE',
      },
    ],
  };
}

/** @param {ReturnType<typeof buildCredits>} credits */
export function renderCreditsMarkdown(credits, projectName) {
  const lines = [
    '# Credits',
    '',
    `<!-- Generated by \`npm run deck\` — do not edit by hand. -->`,
    '',
    `${projectName} is built on freely licensed data and libraries. Each source below is`,
    'used under the license named, and keeps its own copyright.',
    '',
    `Pack version \`${credits.packVersion}\`, generated ${credits.generatedAt}.`,
    '',
  ];

  for (const s of credits.sources) {
    lines.push(`## ${s.name}`, '');
    lines.push(s.description, '');
    lines.push(`- Home: <${s.url}>`);
    if (s.downloadUrl) lines.push(`- Source data: <${s.downloadUrl}>`);
    lines.push(`- License: [${s.license}](${s.licenseUrl})`);
    lines.push('');
  }

  lines.push(
    '---',
    '',
    `${projectName} itself is licensed AGPL-3.0. See [LICENSE](LICENSE).`,
    '',
  );
  return lines.join('\n');
}
